# This is a basic workflow to help you get started with Actions

name: Test variables conditionelles

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        options:
          - dv
          - ap
          - pr

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  configuration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - if: ${{ inputs.ENVIRONMENT == dv }}
        run: |
          echo "var1='en dev'
          " >> $GITHUB_ENV
      - if: ${{ inputs.ENVIRONMENT == ap }}
        run: |
          echo "var1='en app'
          " >> $GITHUB_ENV
      - if: ${{ inputs.ENVIRONMENT == pr }}
        run: |
          echo "var1='en prod'
          " >> $GITHUB_ENV
      - name: Echo la variable dans la même job
        run: echo ${{ env.var1 }}
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: Echo la variable dans une autre job
        run: echo ${{ env.var1 }}
