name: JSON extraction test 
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: choice
        options:
          - DV
          - PR

jobs:
  extractsconfiguration:
    runs-on: ubuntu-latest
    outputs:
      jsonconfiguration: ${{ steps.extraction.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - name: get config dv
        if: ${{ inputs.ENVIRONMENT == 'DV' }}
        id: dv 
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
          path: '.github/workflows/Configuration/dv.json'
          prop_path: 'variable'
      - name: output config dv 
        if: ${{ inputs.ENVIRONMENT == 'DV' }}
        run:  echo "json_tmp='${{ steps.dv.outputs.prop }}'" >> "$GITHUB_ENV"
      - name: get config pr 
        if: ${{ inputs.ENVIRONMENT == 'PR' }}
        id: pr 
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
          path: '.github/workflows/Configuration/pr.json'
          prop_path: 'variable'
      - name: output config dv 
        if: ${{ inputs.ENVIRONMENT == 'PR' }}
        run:  echo "json_tmp='${{ steps.pr.outputs.prop }}'" >> "$GITHUB_ENV"
      - name: extract config
        id: extraction
        run: echo "json=$json_tmp" >> "$GITHUB_OUTPUT"

  shows-configuration:
    runs-on: ubuntu-latest
    needs: extractsconfiguration
    steps:
      - name: Montre la configuration recu
        env:
          CONFIG_VALUE: ${{ needs.extractconfiguration.outputs.jsonconfiguration }}
        run: echo ${{ env.CONFIG_VALUE }}
      
      

