name: JSON extraction test 
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: choice
        options:
          - DV
          - PR

jobs:
  extracts-configuration:
    runs-on: ubuntu-latest
    outputs:
      json_configuration: ${{ steps.extraction.outputs.json }}
    steps:
      - uses: actions/checkout@v3
      - name: get config dv
        if: ${{ inputs.ENVIRONMENT == 'DV' }}
        id: dv 
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
          path: '.github/workflows/Configuration/dv.json'
          prop_path: 'variable'
      - name: output config dv 
        if: ${{ inputs.ENVIRONMENT == 'DV' }}
        run:  echo "json=${{ steps.dv.outputs.prop }}" >> "$GITHUB_OUTPUT"
      - name: get config pr 
        if: ${{ inputs.ENVIRONMENT == 'PR' }}
        id: pr 
        uses: notiz-dev/github-action-json-property@v0.2.0
        with: 
          path: '.github/workflows/Configuration/pr.json'
          prop_path: 'variable'
      - name: output config dv 
        if: ${{ inputs.ENVIRONMENT == 'PR' }}
        run:  echo "json=${{ steps.pr.outputs.prop }}" >> "$GITHUB_OUTPUT"

  shows-configuration:
    runs-on: ubuntu-latest
    needs: extracts-configuration
    steps:
      - name: Montre la configuration recu
        env:
          CONFIG_VALUE: ${{ needs.extract-configuration.outputs.json }}
        run: echo ${{ env.CONFIG_VALUE }}
      
      

