name: Reusable workflow test
on:
  workflow_dispatch:
    inputs:
      VAR_ENV:
        required: true
        type: choice
        options:
          - DV
          - PR


jobs:
  Call-remote-workflow:
    uses: AlexisLessard/gh-reusable-workflow-test/.github/workflows/reusable-workflow.yml@main
    secrets: inherit
    with:
      REMOTE_VAR: ${{ vars.PARAMETER }}
      ENVIRONMENT: testenv
      
  test-dynamic-variables:
      runs-on: ubuntu-latest
      steps:
        - name: Affiche variable dynamique
          run: echo "DYNAMIC VAR ${{ vars[format('TESTVAR_{0}',inputs.VAR_ENV)] }}"
    
